import { useContext } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation } from "react-router-dom";
import { AuthContext } from "./context/AuthContext";
import { BookingProvider } from "./context/BookingContext";
import { Layout } from "./components/layout";
import { LoginPage, RegisterPage } from "./pages/AuthPages";
import { AccountPage, HomePage, ProductsPage, CartPage, SchedulePage, AddressPage, AddressFormPage, PaymentMethodPage, ConfirmationPage, OrdersPage, PaymentPage } from "./pages/CustomerPages";
import { AdminBillingSettings, AdminCustomers, AdminDashboard, AdminInvoices, AdminOrders, AdminUsers } from "./pages/AdminPages";
import { AdminServices } from "./pages/AdminServices";
function Guard({ admin = false, children }) { const { user, loading } = useContext(AuthContext); const location = useLocation(); if (loading) return <p className="state">Loading application...</p>; if (!user) return <Navigate to="/login" replace state={{ from: location.pathname + location.search }} />; if (admin && user.role !== "admin") return <Navigate to="/products" replace />; if (!admin && user.role === "admin") return <Navigate to="/admin" replace />; return <Layout>{children}</Layout>; }
function PublicPage({ children }) { const { user } = useContext(AuthContext); if (user?.role === "admin") return <Navigate to="/admin" replace />; return <Layout>{children}</Layout>; }
function AppRoutes() { return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegisterPage />} /><Route path="/" element={<PublicPage><HomePage /></PublicPage>} /><Route path="/products" element={<PublicPage><ProductsPage /></PublicPage>} /><Route path="/cart" element={<Guard><CartPage /></Guard>} /><Route path="/schedule" element={<Guard><SchedulePage /></Guard>} /><Route path="/addresses" element={<Guard><AddressPage /></Guard>} /><Route path="/addresses/new" element={<Guard><AddressFormPage /></Guard>} /><Route path="/payment-method" element={<Guard><PaymentMethodPage /></Guard>} /><Route path="/confirmation/:id" element={<Guard><ConfirmationPage /></Guard>} /><Route path="/orders" element={<Guard><OrdersPage /></Guard>} /><Route path="/account" element={<Guard><AccountPage /></Guard>} /><Route path="/payment/:id" element={<Guard><PaymentPage /></Guard>} /><Route path="/admin" element={<Guard admin><AdminDashboard /></Guard>} /><Route path="/admin/users" element={<Guard admin><AdminUsers /></Guard>} /><Route path="/admin/customers" element={<Guard admin><AdminCustomers /></Guard>} /><Route path="/admin/invoices" element={<Guard admin><AdminInvoices /></Guard>} /><Route path="/admin/settings" element={<Guard admin><AdminBillingSettings /></Guard>} /><Route path="/admin/services" element={<Guard admin><AdminServices /></Guard>} /><Route path="/admin/products" element={<Navigate to="/admin/services" replace />} /><Route path="/admin/orders" element={<Guard admin><AdminOrders /></Guard>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>; }
export default function App() { return <BrowserRouter><BookingProvider><AppRoutes /></BookingProvider></BrowserRouter>; }
