"use strict";
require("dotenv").config();
const path=require("path");
const express=require("express");
const cookieParser=require("cookie-parser");
const helmet=require("helmet");
const rateLimit=require("express-rate-limit");
const connectDB=require("./config/db");
const {ensureShop}=require("./services/bootstrap");
const {ensureDatabaseIndexes}=require("./services/databaseIndexes");
const {configurePush}=require("./services/push");
const authRoutes=require("./routes/auth");
const profileRoutes=require("./routes/profile");
const ordersRoutes=require("./routes/orders");
const shopRoutes=require("./routes/shop");
const adminRoutes=require("./routes/admin");

const app=express();
configurePush();
const ready=(async()=>{await connectDB();await ensureDatabaseIndexes();await ensureShop();})();
app.ready=ready;
app.disable("x-powered-by");
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:"3mb"}));
app.use(cookieParser());
app.use("/api",async(req,res,next)=>{try{await ready;next();}catch(err){next(err);}});

const otpRequestLimiter=rateLimit({windowMs:60*60*1000,limit:30,standardHeaders:true,legacyHeaders:false,message:{error:"rate_limited",message:"Too many OTP requests from this connection. Try again later."}});
const otpVerifyLimiter=rateLimit({windowMs:15*60*1000,limit:40,standardHeaders:true,legacyHeaders:false,message:{error:"rate_limited",message:"Too many verification attempts. Try again later."}});
app.get("/api/push/public-key",(req,res)=>res.json({publicKey:process.env.VAPID_PUBLIC_KEY}));
app.use("/api/auth/request-otp",otpRequestLimiter);
app.use("/api/auth/verify-otp",otpVerifyLimiter);
app.use("/api/auth",authRoutes);
app.use("/api/me",profileRoutes);
app.use("/api/orders",ordersRoutes);
app.use("/api/shop",shopRoutes);
app.use("/api/admin",adminRoutes);
app.use(express.static(path.join(__dirname,"..","public"),{index:"index.html",maxAge:0}));
app.use("/api",(req,res)=>res.status(404).json({error:"not_found",message:"Unknown API endpoint."}));
app.use((err,req,res,next)=>{console.error("[error] %s %s — %s",req.method,req.originalUrl,err&&err.stack?err.stack:err);if(res.headersSent)return next(err);res.status(500).json({error:"server_error",message:"Something went wrong on the server."});});
module.exports=app;
